/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as InternetOfThingRouteImport } from './routes/internet-of-thing'

const TermsLazyRouteImport = createFileRoute('/terms')()
const SolutionsLazyRouteImport = createFileRoute('/solutions')()
const SoftwareDevelopmentLazyRouteImport = createFileRoute(
  '/software-development',
)()
const ServicesLazyRouteImport = createFileRoute('/services')()
const RealStateLazyRouteImport = createFileRoute('/real-state')()
const ProductsLazyRouteImport = createFileRoute('/products')()
const PrivacyLazyRouteImport = createFileRoute('/privacy')()
const IndustriesLazyRouteImport = createFileRoute('/industries')()
const HybridCloudLazyRouteImport = createFileRoute('/hybrid-cloud')()
const ContactUsLazyRouteImport = createFileRoute('/contact-us')()
const ConstructionLazyRouteImport = createFileRoute('/construction')()
const CloudServiceLazyRouteImport = createFileRoute('/cloud-service')()
const AboutUsLazyRouteImport = createFileRoute('/about-us')()
const IndexLazyRouteImport = createFileRoute('/')()

const TermsLazyRoute = TermsLazyRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/terms.lazy').then((d) => d.Route))
const SolutionsLazyRoute = SolutionsLazyRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/solutions.lazy').then((d) => d.Route))
const SoftwareDevelopmentLazyRoute = SoftwareDevelopmentLazyRouteImport.update({
  id: '/software-development',
  path: '/software-development',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/software-development.lazy').then((d) => d.Route),
)
const ServicesLazyRoute = ServicesLazyRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/services.lazy').then((d) => d.Route))
const RealStateLazyRoute = RealStateLazyRouteImport.update({
  id: '/real-state',
  path: '/real-state',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/real-state.lazy').then((d) => d.Route))
const ProductsLazyRoute = ProductsLazyRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/products.lazy').then((d) => d.Route))
const PrivacyLazyRoute = PrivacyLazyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/privacy.lazy').then((d) => d.Route))
const IndustriesLazyRoute = IndustriesLazyRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/industries.lazy').then((d) => d.Route))
const HybridCloudLazyRoute = HybridCloudLazyRouteImport.update({
  id: '/hybrid-cloud',
  path: '/hybrid-cloud',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/hybrid-cloud.lazy').then((d) => d.Route))
const ContactUsLazyRoute = ContactUsLazyRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact-us.lazy').then((d) => d.Route))
const ConstructionLazyRoute = ConstructionLazyRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/construction.lazy').then((d) => d.Route))
const CloudServiceLazyRoute = CloudServiceLazyRouteImport.update({
  id: '/cloud-service',
  path: '/cloud-service',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cloud-service.lazy').then((d) => d.Route))
const AboutUsLazyRoute = AboutUsLazyRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about-us.lazy').then((d) => d.Route))
const InternetOfThingRoute = InternetOfThingRouteImport.update({
  id: '/internet-of-thing',
  path: '/internet-of-thing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/internet-of-thing': typeof InternetOfThingRoute
  '/about-us': typeof AboutUsLazyRoute
  '/cloud-service': typeof CloudServiceLazyRoute
  '/construction': typeof ConstructionLazyRoute
  '/contact-us': typeof ContactUsLazyRoute
  '/hybrid-cloud': typeof HybridCloudLazyRoute
  '/industries': typeof IndustriesLazyRoute
  '/privacy': typeof PrivacyLazyRoute
  '/products': typeof ProductsLazyRoute
  '/real-state': typeof RealStateLazyRoute
  '/services': typeof ServicesLazyRoute
  '/software-development': typeof SoftwareDevelopmentLazyRoute
  '/solutions': typeof SolutionsLazyRoute
  '/terms': typeof TermsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/internet-of-thing': typeof InternetOfThingRoute
  '/about-us': typeof AboutUsLazyRoute
  '/cloud-service': typeof CloudServiceLazyRoute
  '/construction': typeof ConstructionLazyRoute
  '/contact-us': typeof ContactUsLazyRoute
  '/hybrid-cloud': typeof HybridCloudLazyRoute
  '/industries': typeof IndustriesLazyRoute
  '/privacy': typeof PrivacyLazyRoute
  '/products': typeof ProductsLazyRoute
  '/real-state': typeof RealStateLazyRoute
  '/services': typeof ServicesLazyRoute
  '/software-development': typeof SoftwareDevelopmentLazyRoute
  '/solutions': typeof SolutionsLazyRoute
  '/terms': typeof TermsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/internet-of-thing': typeof InternetOfThingRoute
  '/about-us': typeof AboutUsLazyRoute
  '/cloud-service': typeof CloudServiceLazyRoute
  '/construction': typeof ConstructionLazyRoute
  '/contact-us': typeof ContactUsLazyRoute
  '/hybrid-cloud': typeof HybridCloudLazyRoute
  '/industries': typeof IndustriesLazyRoute
  '/privacy': typeof PrivacyLazyRoute
  '/products': typeof ProductsLazyRoute
  '/real-state': typeof RealStateLazyRoute
  '/services': typeof ServicesLazyRoute
  '/software-development': typeof SoftwareDevelopmentLazyRoute
  '/solutions': typeof SolutionsLazyRoute
  '/terms': typeof TermsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/internet-of-thing'
    | '/about-us'
    | '/cloud-service'
    | '/construction'
    | '/contact-us'
    | '/hybrid-cloud'
    | '/industries'
    | '/privacy'
    | '/products'
    | '/real-state'
    | '/services'
    | '/software-development'
    | '/solutions'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/internet-of-thing'
    | '/about-us'
    | '/cloud-service'
    | '/construction'
    | '/contact-us'
    | '/hybrid-cloud'
    | '/industries'
    | '/privacy'
    | '/products'
    | '/real-state'
    | '/services'
    | '/software-development'
    | '/solutions'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/internet-of-thing'
    | '/about-us'
    | '/cloud-service'
    | '/construction'
    | '/contact-us'
    | '/hybrid-cloud'
    | '/industries'
    | '/privacy'
    | '/products'
    | '/real-state'
    | '/services'
    | '/software-development'
    | '/solutions'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  InternetOfThingRoute: typeof InternetOfThingRoute
  AboutUsLazyRoute: typeof AboutUsLazyRoute
  CloudServiceLazyRoute: typeof CloudServiceLazyRoute
  ConstructionLazyRoute: typeof ConstructionLazyRoute
  ContactUsLazyRoute: typeof ContactUsLazyRoute
  HybridCloudLazyRoute: typeof HybridCloudLazyRoute
  IndustriesLazyRoute: typeof IndustriesLazyRoute
  PrivacyLazyRoute: typeof PrivacyLazyRoute
  ProductsLazyRoute: typeof ProductsLazyRoute
  RealStateLazyRoute: typeof RealStateLazyRoute
  ServicesLazyRoute: typeof ServicesLazyRoute
  SoftwareDevelopmentLazyRoute: typeof SoftwareDevelopmentLazyRoute
  SolutionsLazyRoute: typeof SolutionsLazyRoute
  TermsLazyRoute: typeof TermsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software-development': {
      id: '/software-development'
      path: '/software-development'
      fullPath: '/software-development'
      preLoaderRoute: typeof SoftwareDevelopmentLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-state': {
      id: '/real-state'
      path: '/real-state'
      fullPath: '/real-state'
      preLoaderRoute: typeof RealStateLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hybrid-cloud': {
      id: '/hybrid-cloud'
      path: '/hybrid-cloud'
      fullPath: '/hybrid-cloud'
      preLoaderRoute: typeof HybridCloudLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud-service': {
      id: '/cloud-service'
      path: '/cloud-service'
      fullPath: '/cloud-service'
      preLoaderRoute: typeof CloudServiceLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internet-of-thing': {
      id: '/internet-of-thing'
      path: '/internet-of-thing'
      fullPath: '/internet-of-thing'
      preLoaderRoute: typeof InternetOfThingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  InternetOfThingRoute: InternetOfThingRoute,
  AboutUsLazyRoute: AboutUsLazyRoute,
  CloudServiceLazyRoute: CloudServiceLazyRoute,
  ConstructionLazyRoute: ConstructionLazyRoute,
  ContactUsLazyRoute: ContactUsLazyRoute,
  HybridCloudLazyRoute: HybridCloudLazyRoute,
  IndustriesLazyRoute: IndustriesLazyRoute,
  PrivacyLazyRoute: PrivacyLazyRoute,
  ProductsLazyRoute: ProductsLazyRoute,
  RealStateLazyRoute: RealStateLazyRoute,
  ServicesLazyRoute: ServicesLazyRoute,
  SoftwareDevelopmentLazyRoute: SoftwareDevelopmentLazyRoute,
  SolutionsLazyRoute: SolutionsLazyRoute,
  TermsLazyRoute: TermsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
